version: '3'
services:
  api:
    build: ./api
    volumes:
      -./api:/app
      -/app/node_modules/
      -/app/package-lock.json
      -/app/build
  web:
    build: ./web
    volumes:
      -./web:/app
      -/app/node_modules/
      -/app/package-lock.json
  nginx:
    build: .
    ports:
      -3050:80
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
